version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "development"

  - package-ecosystem: "nuget"
    directory: "/PortalSubastas.Gateway/PortalSubastas.Gateway"
    schedule:
      interval: "weekly"
    target-branch: "development"

  - package-ecosystem: "nuget"
    directory: "/PortalSubastas.Identity"
    schedule:
      interval: "weekly"
    target-branch: "development"

  - package-ecosystem: "nuget"
    directory: "/PortalSubastas.Licitaciones"
    schedule:
      interval: "weekly"
    target-branch: "development"

  - package-ecosystem: "nuget"
    directory: "/PortalSubastas.Providers"
    schedule:
      interval: "weekly"
    target-branch: "development"

  - package-ecosystem: "nuget"
    directory: "/PortalSubastas.Reporting"
    schedule:
      interval: "weekly"
    target-branch: "development"

  - package-ecosystem: "nuget"
    directory: "/PortalSubastas.Audit"
    schedule:
      interval: "weekly"
    target-branch: "development"
