services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: subastas-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: InnovaNow2026!
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  identity-api:
    build:
      context: .
      dockerfile: Dockerfile.Identity
    container_name: subastas-identity
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: admin
      RabbitMq__Password: InnovaNow2026!
    ports:
      - "5001:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  audit-worker:
    build:
      context: .
      dockerfile: Dockerfile.Audit
    container_name: subastas-audit
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: admin
      RabbitMq__Password: InnovaNow2026!
    depends_on:
      rabbitmq:
        condition: service_healthy

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.Gateway
    container_name: subastas-gateway
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: Development
      ReverseProxy__Clusters__IdentityCluster__Destinations__IdentityApi__Address: "http://identity-api:8080"
    ports:
      - "5000:8080"
    depends_on:
      identity-api:
        condition: service_healthy
