// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PortalSubastas.Providers.Domain.Models;

public partial class ProvidersContext : DbContext
{
    public ProvidersContext(DbContextOptions<ProvidersContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TPersona> TPersonas { get; set; }
    public virtual DbSet<TProveedore> TProveedores { get; set; }
    public virtual DbSet<TProveedoresRubro> TProveedoresRubros { get; set; }
    public virtual DbSet<TRubro> TRubros { get; set; }
    public virtual DbSet<TTipoDomicilio> TTiposDomicilio { get; set; }
    public virtual DbSet<TProvincia> TProvincias { get; set; }
    public virtual DbSet<TDomicilio> TDomicilios { get; set; }
    public virtual DbSet<TTiposPersona> TTiposPersonas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresExtension("vector");

        modelBuilder.Entity<TPersona>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_personas_pkey");
            entity.ToTable("t_personas", "iam");

            entity.HasIndex(e => e.NroDocumento, "t_personas_nro_documento_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Apellido).IsRequired().HasMaxLength(100).HasColumnName("apellido");
            entity.Property(e => e.EmailContacto).HasMaxLength(255).HasColumnName("email_contacto");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.IdTipoDocumento).HasColumnName("id_tipo_documento");
            entity.Property(e => e.IdTipoPersona).HasColumnName("id_tipo_persona");
            entity.Property(e => e.Nombre).IsRequired().HasMaxLength(100).HasColumnName("nombre");
            entity.Property(e => e.NroDocumento).IsRequired().HasMaxLength(50).HasColumnName("nro_documento");
            entity.Property(e => e.Telefono).HasMaxLength(50).HasColumnName("telefono");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");

            entity.HasOne(d => d.IdTipoPersonaNavigation).WithMany(p => p.TPersonas)
                .HasForeignKey(d => d.IdTipoPersona)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_personas_id_tipo_persona_fkey");
        });

        modelBuilder.Entity<TProveedore>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_proveedores_pkey");
            entity.ToTable("t_proveedores", "negocio");

            entity.HasIndex(e => e.Cuit, "t_proveedores_cuit_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Cuit).IsRequired().HasMaxLength(20).HasColumnName("cuit");
            entity.Property(e => e.Cup).HasMaxLength(50).HasColumnName("cup");
            entity.Property(e => e.EmailAlternativo).HasMaxLength(255).HasColumnName("email_alternativo");
            entity.Property(e => e.EmailInstitucional).IsRequired().HasMaxLength(255).HasColumnName("email_institucional");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.IdTipoPersona).HasColumnName("id_tipo_persona");
            entity.Property(e => e.RazonSocial).IsRequired().HasMaxLength(255).HasColumnName("razon_social");
            entity.Property(e => e.UrlConstanciaAfip).HasColumnName("url_constancia_afip");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");

            entity.HasOne(d => d.IdTipoPersonaNavigation).WithMany(p => p.TProveedores)
                .HasForeignKey(d => d.IdTipoPersona)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_proveedores_id_tipo_persona_fkey");
        });

        modelBuilder.Entity<TProveedoresRubro>(entity =>
        {
            entity.HasKey(e => new { e.IdProveedor, e.IdRubro }).HasName("t_proveedores_rubros_pkey");
            entity.ToTable("t_proveedores_rubros", "negocio");

            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.IdRubro).HasColumnName("id_rubro");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");

            entity.HasOne(d => d.IdProveedorNavigation).WithMany(p => p.TProveedoresRubros)
                .HasForeignKey(d => d.IdProveedor)
                .HasConstraintName("t_proveedores_rubros_id_proveedor_fkey");

            entity.HasOne(d => d.IdRubroNavigation).WithMany(p => p.TProveedoresRubros)
                .HasForeignKey(d => d.IdRubro)
                .HasConstraintName("t_proveedores_rubros_id_rubro_fkey");
        });

        modelBuilder.Entity<TRubro>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_rubros_pkey");
            entity.ToTable("t_rubros", "negocio");

            entity.HasIndex(e => e.Codigo, "t_rubros_codigo_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Codigo).IsRequired().HasMaxLength(20).HasColumnName("codigo");
            entity.Property(e => e.Descripcion).IsRequired().HasMaxLength(255).HasColumnName("descripcion");
            entity.Property(e => e.IdRubroPadre).HasColumnName("id_rubro_padre");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");

            entity.HasOne(d => d.IdRubroPadreNavigation).WithMany(p => p.Hijos)
                .HasForeignKey(d => d.IdRubroPadre)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_rubros_id_rubro_padre_fkey");
        });

        modelBuilder.Entity<TTipoDomicilio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_tipos_domicilio_pkey");
            entity.ToTable("t_tipos_domicilio", "negocio");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion).IsRequired().HasMaxLength(50).HasColumnName("descripcion");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TProvincia>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_provincias_pkey");
            entity.ToTable("t_provincias", "negocio");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Nombre).IsRequired().HasMaxLength(100).HasColumnName("nombre");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TDomicilio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_domicilios_pkey");
            entity.ToTable("t_domicilios", "negocio");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");
            entity.Property(e => e.IdTipoDomicilio).HasColumnName("id_tipo_domicilio");
            entity.Property(e => e.Calle).IsRequired().HasMaxLength(255).HasColumnName("calle");
            entity.Property(e => e.Numero).IsRequired().HasMaxLength(20).HasColumnName("numero");
            entity.Property(e => e.Piso).HasMaxLength(20).HasColumnName("piso");
            entity.Property(e => e.Departamento).HasMaxLength(20).HasColumnName("departamento");
            entity.Property(e => e.Barrio).IsRequired().HasMaxLength(255).HasColumnName("barrio");
            entity.Property(e => e.Ciudad).IsRequired().HasMaxLength(255).HasColumnName("ciudad");
            entity.Property(e => e.IdProvincia).HasColumnName("id_provincia");
            entity.Property(e => e.CodigoPostal).IsRequired().HasMaxLength(20).HasColumnName("codigo_postal");
            entity.Property(e => e.Telefono).IsRequired().HasMaxLength(50).HasColumnName("telefono");
            entity.Property(e => e.Fax).HasMaxLength(50).HasColumnName("fax");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");

            entity.HasOne(d => d.IdPersonaNavigation).WithMany(p => p.TDomicilios)
                .HasForeignKey(d => d.IdPersona)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_domicilios_id_persona_fkey");

            entity.HasOne(d => d.IdTipoDomicilioNavigation).WithMany(p => p.TDomicilios)
                .HasForeignKey(d => d.IdTipoDomicilio)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_domicilios_id_tipo_domicilio_fkey");

            entity.HasOne(d => d.IdProvinciaNavigation).WithMany(p => p.TDomicilios)
                .HasForeignKey(d => d.IdProvincia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_domicilios_id_provincia_fkey");
        });

        modelBuilder.Entity<TTiposPersona>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_tipos_persona_pkey");
            entity.ToTable("t_tipos_persona", "iam");

            entity.HasIndex(e => e.Descripcion, "t_tipos_persona_descripcion_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion).IsRequired().HasMaxLength(50).HasColumnName("descripcion");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
