// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PortalSubastas.Providers.Domain.Models;

public partial class TProveedore : IFullAuditableEntity
{
    public int Id { get; set; }
    public string RazonSocial { get; set; }
    public string Cuit { get; set; }
    public string Cup { get; set; }
    public string EmailInstitucional { get; set; }
    public string EmailAlternativo { get; set; }
    public int IdTipoPersona { get; set; }
    public string UrlConstanciaAfip { get; set; }
    public string UsrIng { get; set; }
    public DateTime? FecIng { get; set; }
    public string UsrMod { get; set; }
    public DateTime? FecMod { get; set; }
    public string UsrBaja { get; set; }
    public DateTime? FecBaja { get; set; }

    public virtual TTiposPersona IdTipoPersonaNavigation { get; set; }
    public virtual ICollection<TProveedoresRubro> TProveedoresRubros { get; set; } = new List<TProveedoresRubro>();
}
