// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PortalSubastas.Licitaciones.Domain.Models;

public partial class PortalSubastasContext : DbContext
{
    public PortalSubastasContext(DbContextOptions<PortalSubastasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TCatalogosBien> TCatalogosBiens { get; set; }

    public virtual DbSet<TCategoriasProgramatica> TCategoriasProgramaticas { get; set; }

    public virtual DbSet<TEstado> TEstados { get; set; }

    public virtual DbSet<TMonedum> TMoneda { get; set; }

    public virtual DbSet<TObjetosGasto> TObjetosGastos { get; set; }

    public virtual DbSet<TReserva> TReservas { get; set; }

    public virtual DbSet<TReservaDetalle> TReservaDetalles { get; set; }

    public virtual DbSet<TSubResponsable> TSubResponsables { get; set; }

    public virtual DbSet<TUnidadesAdministrativa> TUnidadesAdministrativas { get; set; }

    public virtual DbSet<TVigencia> TVigencias { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TCatalogosBien>(entity =>
        {
            entity.HasKey(e => e.IdItem).HasName("t_catalogos_bien_pkey");

            entity.ToTable("t_catalogos_bien", "negocio");

            entity.HasIndex(e => e.Codigo, "t_catalogos_bien_codigo_key").IsUnique();

            entity.Property(e => e.IdItem).HasColumnName("id_item");
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("codigo");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdItemRel).HasColumnName("id_item_rel");
            entity.Property(e => e.IdObjetoGasto).HasColumnName("id_objeto_gasto");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.NItem)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("n_item");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdItemRelNavigation).WithMany(p => p.InverseIdItemRelNavigation)
                .HasForeignKey(d => d.IdItemRel)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_catalogos_bien_id_item_rel_fkey");

            entity.HasOne(d => d.IdObjetoGastoNavigation).WithMany(p => p.TCatalogosBiens)
                .HasForeignKey(d => d.IdObjetoGasto)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_catalogos_bien_id_objeto_gasto_fkey");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany(p => p.TCatalogosBiens)
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_catalogos_bien_id_vigencia_fkey");
        });

        modelBuilder.Entity<TCategoriasProgramatica>(entity =>
        {
            entity.HasKey(e => e.IdCatProg).HasName("t_categorias_programaticas_pkey");

            entity.ToTable("t_categorias_programaticas", "negocio");

            entity.Property(e => e.IdCatProg).HasColumnName("id_cat_prog");
            entity.Property(e => e.Codigo).HasColumnName("codigo");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdCatProgRel).HasColumnName("id_cat_prog_rel");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.Naturaleza)
                .HasMaxLength(2)
                .HasColumnName("naturaleza");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("nombre");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdCatProgRelNavigation).WithMany(p => p.InverseIdCatProgRelNavigation)
                .HasForeignKey(d => d.IdCatProgRel)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_categorias_programaticas_id_cat_prog_rel_fkey");

            entity.HasOne(d => d.IdUnidadAdmNavigation).WithMany(p => p.TCategoriasProgramaticas)
                .HasForeignKey(d => d.IdUnidadAdm)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_categorias_programaticas_id_unidad_adm_fkey");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany(p => p.TCategoriasProgramaticas)
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_categorias_programaticas_id_vigencia_fkey");
        });

        modelBuilder.Entity<TEstado>(entity =>
        {
            entity.HasKey(e => e.IdEstado).HasName("t_estados_pkey");

            entity.ToTable("t_estados", "negocio");

            entity.Property(e => e.IdEstado).HasColumnName("id_estado");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("tipo");
            entity.Property(e => e.UsrBaja)
                .HasColumnType("character varying")
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnType("character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasColumnType("character varying")
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TMonedum>(entity =>
        {
            entity.HasKey(e => e.IdMoneda).HasName("t_moneda_pkey");

            entity.ToTable("t_moneda", "negocio");

            entity.Property(e => e.IdMoneda).HasColumnName("id_moneda");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(500)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("nombre");
            entity.Property(e => e.Simbolo)
                .HasMaxLength(10)
                .HasColumnName("simbolo");
        });

        modelBuilder.Entity<TObjetosGasto>(entity =>
        {
            entity.HasKey(e => e.IdObjetoGasto).HasName("t_objetos_gasto_pkey");

            entity.ToTable("t_objetos_gasto", "negocio");

            entity.HasIndex(e => e.NumeroObjeto, "t_objetos_gasto_numero_key").IsUnique();

            entity.Property(e => e.IdObjetoGasto).HasColumnName("id_objeto_gasto");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdObjetoGastoRel).HasColumnName("id_objeto_gasto_rel");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.ImputaEjecucion)
                .HasDefaultValue(false)
                .HasColumnName("imputa_ejecucion");
            entity.Property(e => e.NombreObjeto)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nombre_objeto");
            entity.Property(e => e.NumeroObjeto)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("numero_objeto");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdObjetoGastoRelNavigation).WithMany(p => p.InverseIdObjetoGastoRelNavigation)
                .HasForeignKey(d => d.IdObjetoGastoRel)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_objetos_gasto_id_objeto_gasto_rel_fkey");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany(p => p.TObjetosGastos)
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_objetos_gasto_id_vigencia_fkey");
        });

        modelBuilder.Entity<TReserva>(entity =>
        {
            entity.HasKey(e => e.IdReserva).HasName("t_reservas_pkey");

            entity.ToTable("t_reservas", "negocio");

            entity.HasIndex(e => e.NroReserva, "idx_reservas_nro_reserva").IsUnique();

            entity.Property(e => e.IdReserva).HasColumnName("id_reserva");
            entity.Property(e => e.ComentariosUsuarios).HasColumnName("comentarios_usuarios");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.FechaReserva).HasColumnName("fecha_reserva");
            entity.Property(e => e.IdEstado).HasColumnName("id_estado");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdReservaClonar).HasColumnName("id_reserva_clonar");
            entity.Property(e => e.IdSubResponsable).HasColumnName("id_sub_responsable");
            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.MotivoAutorizacion)
                .HasComment("Justificación formal obligatoria ingresada al momento de autorizar la nota de pedido.")
                .HasColumnName("motivo_autorizacion");
            entity.Property(e => e.NroReserva)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("nro_reserva");
            entity.Property(e => e.UsrBaja)
                .HasColumnType("character varying")
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnType("character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasColumnType("character varying")
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdEstadoNavigation).WithMany(p => p.TReservas)
                .HasForeignKey(d => d.IdEstado)
                .HasConstraintName("t_reservas_id_estado_fkey");

            entity.HasOne(d => d.IdReservaClonarNavigation).WithMany(p => p.InverseIdReservaClonarNavigation)
                .HasForeignKey(d => d.IdReservaClonar)
                .HasConstraintName("t_reservas_id_reserva_clonar_fkey");

            entity.HasOne(d => d.IdSubResponsableNavigation).WithMany(p => p.TReservas)
                .HasForeignKey(d => d.IdSubResponsable)
                .HasConstraintName("t_reservas_id_sub_responsable_fkey");

            entity.HasOne(d => d.IdUnidadAdmNavigation).WithMany(p => p.TReservas)
                .HasForeignKey(d => d.IdUnidadAdm)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("t_reservas_id_unidad_adm_fkey");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany(p => p.TReservas)
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("t_reservas_id_vigencia_fkey");
        });

        modelBuilder.Entity<TReservaDetalle>(entity =>
        {
            entity.HasKey(e => e.IdReservaDet).HasName("t_reserva_detalle_pkey");

            entity.ToTable("t_reserva_detalle", "negocio");

            entity.HasIndex(e => e.IdReserva, "idx_reserva_detalle_reserva");

            entity.Property(e => e.IdReservaDet).HasColumnName("id_reserva_det");
            entity.Property(e => e.Cantidad)
                .HasPrecision(15, 4)
                .HasColumnName("cantidad");
            entity.Property(e => e.EspecificacionesTecnicas).HasColumnName("especificaciones_tecnicas");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.FechaEntrega).HasColumnName("fecha_entrega");
            entity.Property(e => e.IdCatProg).HasColumnName("id_cat_prog");
            entity.Property(e => e.IdEstado).HasColumnName("id_estado");
            entity.Property(e => e.IdItem).HasColumnName("id_item");
            entity.Property(e => e.IdMoneda).HasColumnName("id_moneda");
            entity.Property(e => e.IdObjetoGasto).HasColumnName("id_objeto_gasto");
            entity.Property(e => e.IdReserva).HasColumnName("id_reserva");
            entity.Property(e => e.IdReservaDetClonar).HasColumnName("id_reserva_det_clonar");
            entity.Property(e => e.Importe)
                .HasPrecision(15, 2)
                .HasColumnName("importe");
            entity.Property(e => e.ImporteFuturo)
                .HasPrecision(15, 2)
                .HasColumnName("importe_futuro");
            entity.Property(e => e.PlazoEntregaDesde).HasColumnName("plazo_entrega_desde");
            entity.Property(e => e.PlazoEntregaHasta).HasColumnName("plazo_entrega_hasta");
            entity.Property(e => e.UsrBaja)
                .HasColumnType("character varying")
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnType("character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasColumnType("character varying")
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdCatProgNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdCatProg)
                .HasConstraintName("t_reserva_detalle_id_cat_prog_fkey");

            entity.HasOne(d => d.IdEstadoNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdEstado)
                .HasConstraintName("t_reserva_detalle_id_estado_fkey");

            entity.HasOne(d => d.IdItemNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdItem)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("t_reserva_detalle_id_item_fkey");

            entity.HasOne(d => d.IdMonedaNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdMoneda)
                .HasConstraintName("t_reserva_detalle_id_moneda_fkey");

            entity.HasOne(d => d.IdObjetoGastoNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdObjetoGasto)
                .HasConstraintName("t_reserva_detalle_id_objeto_gasto_fkey");

            entity.HasOne(d => d.IdReservaNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdReserva)
                .HasConstraintName("t_reserva_detalle_id_reserva_fkey");

            entity.HasOne(d => d.IdReservaDetClonarNavigation).WithMany(p => p.InverseIdReservaDetClonarNavigation)
                .HasForeignKey(d => d.IdReservaDetClonar)
                .HasConstraintName("t_reserva_detalle_id_reserva_det_clonar_fkey");
        });

        modelBuilder.Entity<TSubResponsable>(entity =>
        {
            entity.HasKey(e => e.IdSubResponsable).HasName("t_sub_responsables_pkey");

            entity.ToTable("t_sub_responsables", "negocio");

            entity.Property(e => e.IdSubResponsable).HasColumnName("id_sub_responsable");
            entity.Property(e => e.Codigo)
                .HasMaxLength(20)
                .HasColumnName("codigo");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdSubRespRel).HasColumnName("id_sub_resp_rel");
            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("nombre");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
            entity.Property(e => e.Vigente)
                .HasDefaultValue(true)
                .HasColumnName("vigente");

            entity.HasOne(d => d.IdSubRespRelNavigation).WithMany(p => p.InverseIdSubRespRelNavigation)
                .HasForeignKey(d => d.IdSubRespRel)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_sub_responsables_id_sub_resp_rel_fkey");

            entity.HasOne(d => d.IdUnidadAdmNavigation).WithMany(p => p.TSubResponsables)
                .HasForeignKey(d => d.IdUnidadAdm)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_sub_responsables_id_unidad_adm_fkey");
        });

        modelBuilder.Entity<TUnidadesAdministrativa>(entity =>
        {
            entity.HasKey(e => e.IdUnidadAdm).HasName("t_unidades_administrativas_pkey");

            entity.ToTable("t_unidades_administrativas", "negocio");

            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");
            entity.Property(e => e.Alias)
                .HasMaxLength(255)
                .HasColumnName("alias");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.Mail)
                .HasMaxLength(255)
                .HasColumnName("mail");
            entity.Property(e => e.NombreUnidadAdm)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nombre_unidad_adm");
            entity.Property(e => e.NroServicioAdm).HasColumnName("nro_servicio_adm");
            entity.Property(e => e.NumeroUnidadAdm).HasColumnName("numero_unidad_adm");
            entity.Property(e => e.Puerto).HasColumnName("puerto");
            entity.Property(e => e.Smtp)
                .HasMaxLength(255)
                .HasColumnName("smtp");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany(p => p.TUnidadesAdministrativas)
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_unidades_administrativas_id_vigencia_fkey");
        });

        modelBuilder.Entity<TVigencia>(entity =>
        {
            entity.HasKey(e => e.IdVigencia).HasName("t_vigencias_pkey");

            entity.ToTable("t_vigencias", "negocio");

            entity.HasIndex(e => e.Ejercicio, "t_vigencias_ejercicio_key").IsUnique();

            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.ActivoEjecucion)
                .HasDefaultValue(false)
                .HasColumnName("activo_ejecucion");
            entity.Property(e => e.Ejercicio).HasColumnName("ejercicio");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.MaximoNivelCp).HasColumnName("maximo_nivel_cp");
            entity.Property(e => e.ProcesoCierre)
                .HasMaxLength(50)
                .HasColumnName("proceso_cierre");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}