// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PortalSubastas.Licitaciones.Domain.Models;

public partial class PortalSubastasContext : DbContext
{
    public PortalSubastasContext(DbContextOptions<PortalSubastasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TCatalogosBien> TCatalogosBiens { get; set; }

    public virtual DbSet<TCategoriasProgramatica> TCategoriasProgramaticas { get; set; }

    public virtual DbSet<TEstado> TEstados { get; set; }

    public virtual DbSet<TMonedum> TMoneda { get; set; }

    public virtual DbSet<TObjetosGasto> TObjetosGastos { get; set; }

    public virtual DbSet<TReserva> TReservas { get; set; }

    public virtual DbSet<TReservaDetalle> TReservaDetalles { get; set; }

    public virtual DbSet<TSubResponsable> TSubResponsables { get; set; }

    public virtual DbSet<TUnidadesAdministrativa> TUnidadesAdministrativas { get; set; }

    public virtual DbSet<TVigencia> TVigencias { get; set; }

    public virtual DbSet<TCotizacion> TCotizaciones { get; set; }
    public virtual DbSet<TCotizacionEspecificacion> TCotizacionEspecificaciones { get; set; }
    public virtual DbSet<TCotizacionDetalle> TCotizacionDetalles { get; set; }
    public virtual DbSet<TCotizacionRenglon> TCotizacionRenglones { get; set; }
    public virtual DbSet<TCotizacionProveedor> TCotizacionProveedores { get; set; }
    public virtual DbSet<TOfertaSubasta> TOfertasSubastas { get; set; }
    public virtual DbSet<TGanador> TGanadores { get; set; }
    public virtual DbSet<TMensaje> TMensajes { get; set; }
    public virtual DbSet<TGarantiaSubasta> TGarantiasSubastas { get; set; }
    public virtual DbSet<TCotizacionDocumento> TCotizacionDocumentos { get; set; }
    public virtual DbSet<TDocumentoItemProveedor> TDocumentoItemProveedores { get; set; }
    public virtual DbSet<TProveedoresRepresentante> TProveedoresRepresentantes { get; set; }
    public virtual DbSet<TPersona> TPersonas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresExtension("vector");

        modelBuilder.Entity<TCatalogosBien>(entity =>
        {
            entity.HasKey(e => e.IdItem).HasName("t_catalogos_bien_pkey");

            entity.ToTable("t_catalogos_bien", "negocio");

            entity.HasIndex(e => e.Codigo, "t_catalogos_bien_codigo_key").IsUnique();

            entity.Property(e => e.IdItem).HasColumnName("id_item");
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("codigo");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdItemRel).HasColumnName("id_item_rel");
            entity.Property(e => e.IdObjetoGasto).HasColumnName("id_objeto_gasto");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.NItem)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("n_item");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdItemRelNavigation).WithMany(p => p.InverseIdItemRelNavigation)
                .HasForeignKey(d => d.IdItemRel)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_catalogos_bien_id_item_rel_fkey");

            entity.HasOne(d => d.IdObjetoGastoNavigation).WithMany(p => p.TCatalogosBiens)
                .HasForeignKey(d => d.IdObjetoGasto)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_catalogos_bien_id_objeto_gasto_fkey");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany(p => p.TCatalogosBiens)
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_catalogos_bien_id_vigencia_fkey");
        });

        modelBuilder.Entity<TCategoriasProgramatica>(entity =>
        {
            entity.HasKey(e => e.IdCatProg).HasName("t_categorias_programaticas_pkey");

            entity.ToTable("t_categorias_programaticas", "negocio");

            entity.Property(e => e.IdCatProg).HasColumnName("id_cat_prog");
            entity.Property(e => e.Codigo).HasColumnName("codigo");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdCatProgRel).HasColumnName("id_cat_prog_rel");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.Naturaleza)
                .HasMaxLength(2)
                .HasColumnName("naturaleza");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("nombre");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdCatProgRelNavigation).WithMany(p => p.InverseIdCatProgRelNavigation)
                .HasForeignKey(d => d.IdCatProgRel)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_categorias_programaticas_id_cat_prog_rel_fkey");

            entity.HasOne(d => d.IdUnidadAdmNavigation).WithMany(p => p.TCategoriasProgramaticas)
                .HasForeignKey(d => d.IdUnidadAdm)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_categorias_programaticas_id_unidad_adm_fkey");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany(p => p.TCategoriasProgramaticas)
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_categorias_programaticas_id_vigencia_fkey");
        });

        modelBuilder.Entity<TEstado>(entity =>
        {
            entity.HasKey(e => e.IdEstado).HasName("t_estados_pkey");

            entity.ToTable("t_estados", "negocio");

            entity.Property(e => e.IdEstado).HasColumnName("id_estado");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("tipo");
            entity.Property(e => e.UsrBaja)
                .HasColumnType("character varying")
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnType("character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasColumnType("character varying")
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TMonedum>(entity =>
        {
            entity.HasKey(e => e.IdMoneda).HasName("t_moneda_pkey");

            entity.ToTable("t_moneda", "negocio");

            entity.Property(e => e.IdMoneda).HasColumnName("id_moneda");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(500)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("nombre");
            entity.Property(e => e.Simbolo)
                .HasMaxLength(10)
                .HasColumnName("simbolo");
        });

        modelBuilder.Entity<TObjetosGasto>(entity =>
        {
            entity.HasKey(e => e.IdObjetoGasto).HasName("t_objetos_gasto_pkey");

            entity.ToTable("t_objetos_gasto", "negocio");

            entity.HasIndex(e => e.NumeroObjeto, "t_objetos_gasto_numero_key").IsUnique();

            entity.Property(e => e.IdObjetoGasto).HasColumnName("id_objeto_gasto");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdObjetoGastoRel).HasColumnName("id_objeto_gasto_rel");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.ImputaEjecucion)
                .HasDefaultValue(false)
                .HasColumnName("imputa_ejecucion");
            entity.Property(e => e.NombreObjeto)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nombre_objeto");
            entity.Property(e => e.NumeroObjeto)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("numero_objeto");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdObjetoGastoRelNavigation).WithMany(p => p.InverseIdObjetoGastoRelNavigation)
                .HasForeignKey(d => d.IdObjetoGastoRel)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_objetos_gasto_id_objeto_gasto_rel_fkey");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany(p => p.TObjetosGastos)
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_objetos_gasto_id_vigencia_fkey");
        });

        modelBuilder.Entity<TReserva>(entity =>
        {
            entity.HasKey(e => e.IdReserva).HasName("t_reservas_pkey");

            entity.ToTable("t_reservas", "negocio");

            entity.HasIndex(e => e.NroReserva, "idx_reservas_nro_reserva").IsUnique();

            entity.Property(e => e.IdReserva).HasColumnName("id_reserva");
            entity.Property(e => e.ComentariosUsuarios).HasColumnName("comentarios_usuarios");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.FechaReserva).HasColumnName("fecha_reserva");
            entity.Property(e => e.IdEstado).HasColumnName("id_estado");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdReservaClonar).HasColumnName("id_reserva_clonar");
            entity.Property(e => e.IdSubResponsable).HasColumnName("id_sub_responsable");
            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.MotivoAutorizacion)
                .HasComment("Justificación formal obligatoria ingresada al momento de autorizar la nota de pedido.")
                .HasColumnName("motivo_autorizacion");
            entity.Property(e => e.NroReserva)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("nro_reserva");
            entity.Property(e => e.UsrBaja)
                .HasColumnType("character varying")
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnType("character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasColumnType("character varying")
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdEstadoNavigation).WithMany(p => p.TReservas)
                .HasForeignKey(d => d.IdEstado)
                .HasConstraintName("t_reservas_id_estado_fkey");

            entity.HasOne(d => d.IdReservaClonarNavigation).WithMany(p => p.InverseIdReservaClonarNavigation)
                .HasForeignKey(d => d.IdReservaClonar)
                .HasConstraintName("t_reservas_id_reserva_clonar_fkey");

            entity.HasOne(d => d.IdSubResponsableNavigation).WithMany(p => p.TReservas)
                .HasForeignKey(d => d.IdSubResponsable)
                .HasConstraintName("t_reservas_id_sub_responsable_fkey");

            entity.HasOne(d => d.IdUnidadAdmNavigation).WithMany(p => p.TReservas)
                .HasForeignKey(d => d.IdUnidadAdm)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("t_reservas_id_unidad_adm_fkey");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany(p => p.TReservas)
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("t_reservas_id_vigencia_fkey");
        });

        modelBuilder.Entity<TReservaDetalle>(entity =>
        {
            entity.HasKey(e => e.IdReservaDet).HasName("t_reserva_detalle_pkey");

            entity.ToTable("t_reserva_detalle", "negocio");

            entity.HasIndex(e => e.IdReserva, "idx_reserva_detalle_reserva");

            entity.Property(e => e.IdReservaDet).HasColumnName("id_reserva_det");
            entity.Property(e => e.Cantidad)
                .HasPrecision(15, 4)
                .HasColumnName("cantidad");
            entity.Property(e => e.EspecificacionesTecnicas).HasColumnName("especificaciones_tecnicas");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.FechaEntrega).HasColumnName("fecha_entrega");
            entity.Property(e => e.IdCatProg).HasColumnName("id_cat_prog");
            entity.Property(e => e.IdEstado).HasColumnName("id_estado");
            entity.Property(e => e.IdItem).HasColumnName("id_item");
            entity.Property(e => e.IdMoneda).HasColumnName("id_moneda");
            entity.Property(e => e.IdObjetoGasto).HasColumnName("id_objeto_gasto");
            entity.Property(e => e.IdReserva).HasColumnName("id_reserva");
            entity.Property(e => e.IdReservaDetClonar).HasColumnName("id_reserva_det_clonar");
            entity.Property(e => e.Importe)
                .HasPrecision(15, 2)
                .HasColumnName("importe");
            entity.Property(e => e.ImporteFuturo)
                .HasPrecision(15, 2)
                .HasColumnName("importe_futuro");
            entity.Property(e => e.PlazoEntregaDesde).HasColumnName("plazo_entrega_desde");
            entity.Property(e => e.PlazoEntregaHasta).HasColumnName("plazo_entrega_hasta");
            entity.Property(e => e.UsrBaja)
                .HasColumnType("character varying")
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnType("character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasColumnType("character varying")
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdCatProgNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdCatProg)
                .HasConstraintName("t_reserva_detalle_id_cat_prog_fkey");

            entity.HasOne(d => d.IdEstadoNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdEstado)
                .HasConstraintName("t_reserva_detalle_id_estado_fkey");

            entity.HasOne(d => d.IdItemNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdItem)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("t_reserva_detalle_id_item_fkey");

            entity.HasOne(d => d.IdMonedaNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdMoneda)
                .HasConstraintName("t_reserva_detalle_id_moneda_fkey");

            entity.HasOne(d => d.IdObjetoGastoNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdObjetoGasto)
                .HasConstraintName("t_reserva_detalle_id_objeto_gasto_fkey");

            entity.HasOne(d => d.IdReservaNavigation).WithMany(p => p.TReservaDetalles)
                .HasForeignKey(d => d.IdReserva)
                .HasConstraintName("t_reserva_detalle_id_reserva_fkey");

            entity.HasOne(d => d.IdReservaDetClonarNavigation).WithMany(p => p.InverseIdReservaDetClonarNavigation)
                .HasForeignKey(d => d.IdReservaDetClonar)
                .HasConstraintName("t_reserva_detalle_id_reserva_det_clonar_fkey");
        });

        modelBuilder.Entity<TSubResponsable>(entity =>
        {
            entity.HasKey(e => e.IdSubResponsable).HasName("t_sub_responsables_pkey");

            entity.ToTable("t_sub_responsables", "negocio");

            entity.Property(e => e.IdSubResponsable).HasColumnName("id_sub_responsable");
            entity.Property(e => e.Codigo)
                .HasMaxLength(20)
                .HasColumnName("codigo");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdSubRespRel).HasColumnName("id_sub_resp_rel");
            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("nombre");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
            entity.Property(e => e.Vigente)
                .HasDefaultValue(true)
                .HasColumnName("vigente");

            entity.HasOne(d => d.IdSubRespRelNavigation).WithMany(p => p.InverseIdSubRespRelNavigation)
                .HasForeignKey(d => d.IdSubRespRel)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_sub_responsables_id_sub_resp_rel_fkey");

            entity.HasOne(d => d.IdUnidadAdmNavigation).WithMany(p => p.TSubResponsables)
                .HasForeignKey(d => d.IdUnidadAdm)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_sub_responsables_id_unidad_adm_fkey");
        });

        modelBuilder.Entity<TUnidadesAdministrativa>(entity =>
        {
            entity.HasKey(e => e.IdUnidadAdm).HasName("t_unidades_administrativas_pkey");

            entity.ToTable("t_unidades_administrativas", "negocio");

            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");
            entity.Property(e => e.Alias)
                .HasMaxLength(255)
                .HasColumnName("alias");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.Mail)
                .HasMaxLength(255)
                .HasColumnName("mail");
            entity.Property(e => e.NombreUnidadAdm)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nombre_unidad_adm");
            entity.Property(e => e.NroServicioAdm).HasColumnName("nro_servicio_adm");
            entity.Property(e => e.NumeroUnidadAdm).HasColumnName("numero_unidad_adm");
            entity.Property(e => e.Puerto).HasColumnName("puerto");
            entity.Property(e => e.Smtp)
                .HasMaxLength(255)
                .HasColumnName("smtp");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany(p => p.TUnidadesAdministrativas)
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_unidades_administrativas_id_vigencia_fkey");
        });

        modelBuilder.Entity<TVigencia>(entity =>
        {
            entity.HasKey(e => e.IdVigencia).HasName("t_vigencias_pkey");

            entity.ToTable("t_vigencias", "negocio");

            entity.HasIndex(e => e.Ejercicio, "t_vigencias_ejercicio_key").IsUnique();

            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.ActivoEjecucion)
                .HasDefaultValue(false)
                .HasColumnName("activo_ejecucion");
            entity.Property(e => e.Ejercicio).HasColumnName("ejercicio");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.MaximoNivelCp).HasColumnName("maximo_nivel_cp");
            entity.Property(e => e.ProcesoCierre)
                .HasMaxLength(50)
                .HasColumnName("proceso_cierre");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TCotizacion>(entity =>
        {
            entity.HasKey(e => e.IdCotizacion).HasName("t_cotizacion_pkey");
            entity.ToTable("t_cotizacion", "negocio");

            entity.Property(e => e.IdCotizacion).HasColumnName("id_cotizacion");
            entity.Property(e => e.NroCotizacion).IsRequired().HasMaxLength(20).HasColumnName("nro_cotizacion");
            entity.Property(e => e.IdEstado).HasColumnName("id_estado");
            entity.Property(e => e.IdTipoContratacion).HasColumnName("id_tipo_contratacion");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");
            entity.Property(e => e.Observacion).HasColumnName("observacion");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            
            entity.HasOne(d => d.Especificacion).WithOne(p => p.IdCotizacionNavigation).HasForeignKey<TCotizacionEspecificacion>(d => d.IdCotizacion).OnDelete(DeleteBehavior.Cascade);
            entity.HasOne(d => d.IdUnidadAdmNavigation).WithMany().HasForeignKey(d => d.IdUnidadAdm).OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<TCotizacionEspecificacion>(entity =>
        {
            entity.HasKey(e => e.IdCotEspecificacion).HasName("t_cotizacion_especificacion_pkey");
            entity.ToTable("t_cotizacion_especificacion", "negocio");

            entity.Property(e => e.IdCotEspecificacion).HasColumnName("id_cot_especificacion");
            entity.Property(e => e.IdCotizacion).HasColumnName("id_cotizacion");
            entity.Property(e => e.FechaInicioSubasta).HasColumnType("timestamp without time zone").HasColumnName("fecha_inicio_subasta");
            entity.Property(e => e.FechaFinalizacionSubasta).HasColumnType("timestamp without time zone").HasColumnName("fecha_finalizacion_subasta");
            entity.Property(e => e.FechaLimiteConsultas).HasColumnType("timestamp without time zone").HasColumnName("fecha_limite_consultas");
            entity.Property(e => e.MargenMejora).HasColumnType("numeric(18,2)").HasColumnName("margen_mejora");
            entity.Property(e => e.CriterioAdjudicacion).HasColumnName("criterio_adjudicacion");
            entity.Property(e => e.PermiteProrroga).HasColumnName("permite_prorroga");
            entity.Property(e => e.ProrrogaMinutos).HasColumnName("prorroga_minutos");
            entity.Property(e => e.NroExpediente).HasMaxLength(50).HasColumnName("nro_expediente");
            entity.Property(e => e.Redeterminacion).HasMaxLength(1).HasColumnName("redeterminacion");
            entity.Property(e => e.TipoSobre).HasMaxLength(1).HasColumnName("tipo_sobre");
            entity.Property(e => e.FechaLimiteImpugnar).HasColumnType("timestamp without time zone").HasColumnName("fecha_limite_impugnar");
            entity.Property(e => e.FechaAperturaSobreUno).HasColumnType("timestamp without time zone").HasColumnName("fecha_apertura_sobre_uno");
            entity.Property(e => e.FechaAperturaSobreDos).HasColumnType("timestamp without time zone").HasColumnName("fecha_apertura_sobre_dos");
            entity.Property(e => e.MostrarBotonMejora).HasColumnName("mostrar_boton_mejora");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
        });

        modelBuilder.Entity<TCotizacionDetalle>(entity =>
        {
            entity.HasKey(e => e.IdCotizacionDetalle).HasName("t_cotizacion_detalle_pkey");
            entity.ToTable("t_cotizacion_detalle", "negocio");

            entity.Property(e => e.IdCotizacionDetalle).HasColumnName("id_cotizacion_detalle");
            entity.Property(e => e.IdCotizacion).HasColumnName("id_cotizacion");
            entity.Property(e => e.IdReservaDetalle).HasColumnName("id_reserva_detalle");
            entity.Property(e => e.IdItem).HasColumnName("id_item");
            entity.Property(e => e.IdRenglon).HasColumnName("id_renglon");
            entity.Property(e => e.Cantidad).HasColumnType("numeric(18,2)").HasColumnName("cantidad");
            entity.Property(e => e.ImporteBase).HasColumnType("numeric(18,2)").HasColumnName("importe_base");
            entity.Property(e => e.ImporteMinimo).HasColumnType("numeric(18,2)").HasColumnName("importe_minimo");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdCotizacionNavigation).WithMany(p => p.Detalles).HasForeignKey(d => d.IdCotizacion).OnDelete(DeleteBehavior.Cascade);
            entity.HasOne(d => d.IdRenglonNavigation).WithMany(p => p.Detalles).HasForeignKey(d => d.IdRenglon).OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<TCotizacionRenglon>(entity =>
        {
            entity.HasKey(e => e.IdRenglon).HasName("t_cotizacion_renglon_pkey");
            entity.ToTable("t_cotizacion_renglon", "negocio");

            entity.Property(e => e.IdRenglon).HasColumnName("id_renglon");
            entity.Property(e => e.IdCotizacion).HasColumnName("id_cotizacion");
            entity.Property(e => e.NumeroRenglon).HasColumnName("numero_renglon");
            entity.Property(e => e.Descripcion).HasMaxLength(500).HasColumnName("descripcion");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdCotizacionNavigation).WithMany(p => p.Renglones).HasForeignKey(d => d.IdCotizacion).OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<TCotizacionProveedor>(entity =>
        {
            entity.HasKey(e => e.IdCotizacionProveedor).HasName("t_cotizacion_proveedor_pkey");
            entity.ToTable("t_cotizacion_proveedor", "negocio");

            entity.Property(e => e.IdCotizacionProveedor).HasColumnName("id_cotizacion_proveedor");
            entity.Property(e => e.IdCotizacion).HasColumnName("id_cotizacion");
            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.Ganadora).HasMaxLength(1).HasColumnName("ganadora");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdCotizacionNavigation).WithMany(p => p.Proveedores).HasForeignKey(d => d.IdCotizacion).OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<TOfertaSubasta>(entity =>
        {
            entity.HasKey(e => e.IdOfertaSubasta).HasName("t_ofertas_subasta_pkey");
            entity.ToTable("t_ofertas_subasta", "negocio");

            entity.Property(e => e.IdOfertaSubasta).HasColumnName("id_oferta_subasta");
            entity.Property(e => e.IdCotizacion).HasColumnName("id_cotizacion");
            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.IdCotizacionDetalle).HasColumnName("id_cotizacion_detalle");
            entity.Property(e => e.IdRenglon).HasColumnName("id_renglon");
            entity.Property(e => e.Monto).HasColumnType("numeric(18,2)").HasColumnName("monto");
            entity.Property(e => e.FechaOferta).HasColumnType("timestamp without time zone").HasColumnName("fecha_oferta");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdCotizacionNavigation).WithMany(p => p.Ofertas).HasForeignKey(d => d.IdCotizacion).OnDelete(DeleteBehavior.Cascade);
            entity.HasOne(d => d.IdCotizacionDetalleNavigation).WithMany().HasForeignKey(d => d.IdCotizacionDetalle).OnDelete(DeleteBehavior.SetNull);
            entity.HasOne(d => d.IdRenglonNavigation).WithMany().HasForeignKey(d => d.IdRenglon).OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<TGanador>(entity =>
        {
            entity.HasKey(e => e.IdGanador).HasName("t_ganador_pkey");
            entity.ToTable("t_ganador", "negocio");

            entity.Property(e => e.IdGanador).HasColumnName("id_ganador");
            entity.Property(e => e.IdCotizacion).HasColumnName("id_cotizacion");
            entity.Property(e => e.IdCotizacionDetalle).HasColumnName("id_cotizacion_detalle");
            entity.Property(e => e.IdRenglon).HasColumnName("id_renglon");
            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.MontoGanador).HasColumnType("numeric(18,2)").HasColumnName("monto_ganador");
            entity.Property(e => e.CantidadAdjudicada).HasColumnType("numeric(18,2)").HasColumnName("cantidad_adjudicada");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdCotizacionNavigation).WithMany().HasForeignKey(d => d.IdCotizacion).OnDelete(DeleteBehavior.Cascade);
            entity.HasOne(d => d.IdCotizacionDetalleNavigation).WithMany(p => p.Ganadores).HasForeignKey(d => d.IdCotizacionDetalle).OnDelete(DeleteBehavior.SetNull);
            entity.HasOne(d => d.IdRenglonNavigation).WithMany().HasForeignKey(d => d.IdRenglon).OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<TMensaje>(entity =>
        {
            entity.HasKey(e => e.IdMensaje).HasName("t_mensajes_pkey");
            entity.ToTable("t_mensajes", "negocio");

            entity.Property(e => e.IdMensaje).HasColumnName("id_mensaje");
            entity.Property(e => e.IdCotizacion).HasColumnName("id_cotizacion");
            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.Usuario).IsRequired().HasMaxLength(100).HasColumnName("usuario");
            entity.Property(e => e.Contenido).IsRequired().HasColumnType("text").HasColumnName("contenido");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");

            entity.Property(e => e.Respuesta).HasColumnType("text").HasColumnName("respuesta");
            entity.Property(e => e.FechaRespuesta).HasColumnType("timestamp without time zone").HasColumnName("fecha_respuesta");
            entity.Property(e => e.UsuarioRespuesta).HasMaxLength(100).HasColumnName("usuario_respuesta");

            entity.HasOne(d => d.IdCotizacionNavigation).WithMany().HasForeignKey(d => d.IdCotizacion).OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<TGarantiaSubasta>(entity =>
        {
            entity.HasKey(e => e.IdGarantia).HasName("t_garantias_subasta_pkey");
            entity.ToTable("t_garantias_subasta", "negocio");

            entity.Property(e => e.IdGarantia).HasColumnName("id_garantia");
            entity.Property(e => e.IdCotizacion).HasColumnName("id_cotizacion");
            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.IdTipoDocumento).HasColumnName("id_tipo_documento");
            entity.Property(e => e.IdMoneda).HasColumnName("id_moneda");
            entity.Property(e => e.CompaniaAseguradora).HasMaxLength(255).HasColumnName("compania_aseguradora");
            entity.Property(e => e.NroPoliza).HasMaxLength(100).HasColumnName("nro_poliza");
            entity.Property(e => e.MontoCaucion).HasColumnType("numeric(18,2)").HasColumnName("monto_caucion");
            entity.Property(e => e.MontoPagare).HasColumnType("numeric(18,2)").HasColumnName("monto_pagare");
            entity.Property(e => e.FechaPagare).HasColumnName("fecha_pagare");
            entity.Property(e => e.Observacion).HasColumnName("observacion");
            entity.Property(e => e.UrlArchivo).IsRequired().HasMaxLength(500).HasColumnName("url_archivo");
            entity.Property(e => e.NombreArchivo).HasMaxLength(255).HasColumnName("nombre_archivo");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdCotizacionNavigation).WithMany().HasForeignKey(d => d.IdCotizacion).OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<TCotizacionDocumento>(entity =>
        {
            entity.HasKey(e => e.IdCotDocumento).HasName("t_cotizacion_documento_pkey");
            entity.ToTable("t_cotizacion_documento", "negocio");

            entity.Property(e => e.IdCotDocumento).HasColumnName("id_cot_documento");
            entity.Property(e => e.IdCotizacion).HasColumnName("id_cotizacion");
            entity.Property(e => e.TipoDocumento).IsRequired().HasMaxLength(50).HasColumnName("tipo_documento");
            entity.Property(e => e.NombreArchivo).IsRequired().HasMaxLength(255).HasColumnName("nombre_archivo");
            entity.Property(e => e.UrlArchivo).IsRequired().HasMaxLength(500).HasColumnName("url_archivo");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");

            // FIX: Declaramos explícitamente que estas columnas aceptan NULL en la base de datos
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod").IsRequired(false);
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja").IsRequired(false);
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdCotizacionNavigation).WithMany().HasForeignKey(d => d.IdCotizacion).OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<TDocumentoItemProveedor>(entity =>
        {
            entity.HasKey(e => e.IdDocItem).HasName("t_documento_item_proveedor_pkey");
            entity.ToTable("t_documento_item_proveedor", "negocio");

            entity.Property(e => e.IdDocItem).HasColumnName("id_doc_item");
            entity.Property(e => e.IdCotizacion).HasColumnName("id_cotizacion");
            entity.Property(e => e.IdCotizacionDetalle).HasColumnName("id_cotizacion_detalle");
            entity.Property(e => e.IdRenglon).HasColumnName("id_renglon");
            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");

            entity.Property(e => e.NombreArchivo).IsRequired().HasMaxLength(255).HasColumnName("nombre_archivo");
            entity.Property(e => e.UrlArchivo).IsRequired().HasMaxLength(500).HasColumnName("url_archivo");
            entity.Property(e => e.Enviado).HasDefaultValue(false).HasColumnName("enviado");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod").IsRequired(false);
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja").IsRequired(false);
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdCotizacionNavigation).WithMany().HasForeignKey(d => d.IdCotizacion).OnDelete(DeleteBehavior.Cascade);
            entity.HasOne(d => d.IdCotizacionDetalleNavigation).WithMany().HasForeignKey(d => d.IdCotizacionDetalle).OnDelete(DeleteBehavior.SetNull);
            entity.HasOne(d => d.IdRenglonNavigation).WithMany().HasForeignKey(d => d.IdRenglon).OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<TProveedoresRepresentante>(entity =>
        {
            entity.HasKey(e => new { e.IdProveedor, e.IdPersona }).HasName("t_proveedores_representantes_pkey");

            entity.ToTable("t_proveedores_representantes", "negocio");

            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdPersonaNavigation)
                .WithMany(p => p.TProveedoresRepresentantes)
                .HasForeignKey(d => d.IdPersona)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_proveedores_representantes_id_persona_fkey");
        });

        modelBuilder.Entity<TPersona>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_personas_pkey");

            entity.ToTable("t_personas", "iam");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Nombre).HasMaxLength(255).HasColumnName("nombre");
            entity.Property(e => e.Apellido).HasMaxLength(255).HasColumnName("apellido");
            entity.Property(e => e.EmailContacto).HasMaxLength(255).HasColumnName("email_contacto");

            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}