// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using PortalSubastas.Licitaciones.Domain.Auditable;
using System;
using System.Collections.Generic;

namespace PortalSubastas.Licitaciones.Domain.Models;

public partial class TCatalogosBien : IFullAuditableEntity
{
    public int IdItem { get; set; }

    public int? IdItemRel { get; set; }

    public string Codigo { get; set; }

    public string NItem { get; set; }

    public int IdVigencia { get; set; }

    public int? IdOrganizacion { get; set; }

    public int? IdObjetoGasto { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public virtual TCatalogosBien IdItemRelNavigation { get; set; }

    public virtual TObjetosGasto IdObjetoGastoNavigation { get; set; }

    public virtual TVigencia IdVigenciaNavigation { get; set; }

    public virtual ICollection<TCatalogosBien> InverseIdItemRelNavigation { get; set; } = new List<TCatalogosBien>();

    public virtual ICollection<TReservaDetalle> TReservaDetalles { get; set; } = new List<TReservaDetalle>();
}