// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using PortalSubastas.Licitaciones.Domain.Auditable;
using System;
using System.Collections.Generic;

namespace PortalSubastas.Licitaciones.Domain.Models;

public partial class TCategoriasProgramatica : IFullAuditableEntity
{
    public int IdCatProg { get; set; }

    public int? IdCatProgRel { get; set; }

    public int? IdOrganizacion { get; set; }

    public int? IdUnidadAdm { get; set; }

    public int IdVigencia { get; set; }

    public int Codigo { get; set; }

    public string Nombre { get; set; }

    public string Naturaleza { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public virtual TCategoriasProgramatica IdCatProgRelNavigation { get; set; }

    public virtual TUnidadesAdministrativa IdUnidadAdmNavigation { get; set; }

    public virtual TVigencia IdVigenciaNavigation { get; set; }

    public virtual ICollection<TCategoriasProgramatica> InverseIdCatProgRelNavigation { get; set; } = new List<TCategoriasProgramatica>();

    public virtual ICollection<TReservaDetalle> TReservaDetalles { get; set; } = new List<TReservaDetalle>();
}