// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using PortalSubastas.Licitaciones.Domain.Auditable;
using System;
using System.Collections.Generic;

namespace PortalSubastas.Licitaciones.Domain.Models;

public partial class TEstado : IFullAuditableEntity
{
    public int IdEstado { get; set; }

    public string Descripcion { get; set; }

    public string Tipo { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public virtual ICollection<TReservaDetalle> TReservaDetalles { get; set; } = new List<TReservaDetalle>();

    public virtual ICollection<TReserva> TReservas { get; set; } = new List<TReserva>();
}