// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using PortalSubastas.Licitaciones.Domain.Auditable;
using System;
using System.Collections.Generic;

namespace PortalSubastas.Licitaciones.Domain.Models;

public partial class TObjetosGasto : IFullAuditableEntity
{
    public int IdObjetoGasto { get; set; }

    public int? IdObjetoGastoRel { get; set; }

    public string NumeroObjeto { get; set; }

    public string NombreObjeto { get; set; }

    public int IdVigencia { get; set; }

    public int? IdOrganizacion { get; set; }

    public bool? ImputaEjecucion { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public virtual TObjetosGasto IdObjetoGastoRelNavigation { get; set; }

    public virtual TVigencia IdVigenciaNavigation { get; set; }

    public virtual ICollection<TObjetosGasto> InverseIdObjetoGastoRelNavigation { get; set; } = new List<TObjetosGasto>();

    public virtual ICollection<TCatalogosBien> TCatalogosBiens { get; set; } = new List<TCatalogosBien>();

    public virtual ICollection<TReservaDetalle> TReservaDetalles { get; set; } = new List<TReservaDetalle>();
}