// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using PortalSubastas.Licitaciones.Domain.Auditable;
using System;
using System.Collections.Generic;

namespace PortalSubastas.Licitaciones.Domain.Models;

public partial class TReservaDetalle : IFullAuditableEntity
{
    public int IdReservaDet { get; set; }

    public int IdReserva { get; set; }

    public int? IdCatProg { get; set; }

    public int IdItem { get; set; }

    public int? IdMoneda { get; set; }

    public int? IdObjetoGasto { get; set; }

    public decimal? Cantidad { get; set; }

    public decimal? Importe { get; set; }

    public decimal? ImporteFuturo { get; set; }

    public string EspecificacionesTecnicas { get; set; }

    public DateOnly? FechaEntrega { get; set; }

    public DateOnly? PlazoEntregaDesde { get; set; }

    public DateOnly? PlazoEntregaHasta { get; set; }

    public int? IdEstado { get; set; }

    public int? IdReservaDetClonar { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public virtual TCategoriasProgramatica IdCatProgNavigation { get; set; }

    public virtual TEstado IdEstadoNavigation { get; set; }

    public virtual TCatalogosBien IdItemNavigation { get; set; }

    public virtual TMonedum IdMonedaNavigation { get; set; }

    public virtual TObjetosGasto IdObjetoGastoNavigation { get; set; }

    public virtual TReservaDetalle IdReservaDetClonarNavigation { get; set; }

    public virtual TReserva IdReservaNavigation { get; set; }

    public virtual ICollection<TReservaDetalle> InverseIdReservaDetClonarNavigation { get; set; } = new List<TReservaDetalle>();
}