// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using PortalSubastas.Licitaciones.Domain.Auditable;
using System;
using System.Collections.Generic;

namespace PortalSubastas.Licitaciones.Domain.Models;

public partial class TReserva : IFullAuditableEntity
{
    public int IdReserva { get; set; }

    public string NroReserva { get; set; }

    public int IdVigencia { get; set; }

    public int IdUnidadAdm { get; set; }

    public int? IdSubResponsable { get; set; }

    public int? IdOrganizacion { get; set; }

    public int? IdEstado { get; set; }

    public DateOnly FechaReserva { get; set; }

    public string ComentariosUsuarios { get; set; }

    public int? IdReservaClonar { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    /// <summary>
    /// Justificación formal obligatoria ingresada al momento de autorizar la nota de pedido.
    /// </summary>
    public string MotivoAutorizacion { get; set; }

    public virtual TEstado IdEstadoNavigation { get; set; }

    public virtual TReserva IdReservaClonarNavigation { get; set; }

    public virtual TSubResponsable IdSubResponsableNavigation { get; set; }

    public virtual TUnidadesAdministrativa IdUnidadAdmNavigation { get; set; }

    public virtual TVigencia IdVigenciaNavigation { get; set; }

    public virtual ICollection<TReserva> InverseIdReservaClonarNavigation { get; set; } = new List<TReserva>();

    public virtual ICollection<TReservaDetalle> TReservaDetalles { get; set; } = new List<TReservaDetalle>();
}