// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using PortalSubastas.Licitaciones.Domain.Auditable;
using System;
using System.Collections.Generic;

namespace PortalSubastas.Licitaciones.Domain.Models;

public partial class TSubResponsable : IFullAuditableEntity
{
    public int IdSubResponsable { get; set; }

    public int? IdSubRespRel { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public bool? Vigente { get; set; }

    public int? IdUnidadAdm { get; set; }

    public virtual TSubResponsable IdSubRespRelNavigation { get; set; }

    public virtual TUnidadesAdministrativa IdUnidadAdmNavigation { get; set; }

    public virtual ICollection<TSubResponsable> InverseIdSubRespRelNavigation { get; set; } = new List<TSubResponsable>();

    public virtual ICollection<TReserva> TReservas { get; set; } = new List<TReserva>();
}