// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using PortalSubastas.Licitaciones.Domain.Auditable;
using System;
using System.Collections.Generic;

namespace PortalSubastas.Licitaciones.Domain.Models;

public partial class TUnidadesAdministrativa : IFullAuditableEntity
{
    public int IdUnidadAdm { get; set; }

    public int NumeroUnidadAdm { get; set; }

    public string NombreUnidadAdm { get; set; }

    public int IdVigencia { get; set; }

    public int? IdOrganizacion { get; set; }

    public int? NroServicioAdm { get; set; }

    public int? IdProveedor { get; set; }

    public string Mail { get; set; }

    public string Alias { get; set; }

    public short? Puerto { get; set; }

    public string Smtp { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public virtual TVigencia IdVigenciaNavigation { get; set; }

    public virtual ICollection<TCategoriasProgramatica> TCategoriasProgramaticas { get; set; } = new List<TCategoriasProgramatica>();

    public virtual ICollection<TReserva> TReservas { get; set; } = new List<TReserva>();

    public virtual ICollection<TSubResponsable> TSubResponsables { get; set; } = new List<TSubResponsable>();
}