// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using PortalSubastas.Licitaciones.Domain.Auditable;
using System;
using System.Collections.Generic;

namespace PortalSubastas.Licitaciones.Domain.Models;

public partial class TVigencia : IFullAuditableEntity
{
    public int IdVigencia { get; set; }

    public short Ejercicio { get; set; }

    public bool? ActivoEjecucion { get; set; }

    public short? MaximoNivelCp { get; set; }

    public string ProcesoCierre { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public virtual ICollection<TCatalogosBien> TCatalogosBiens { get; set; } = new List<TCatalogosBien>();

    public virtual ICollection<TCategoriasProgramatica> TCategoriasProgramaticas { get; set; } = new List<TCategoriasProgramatica>();

    public virtual ICollection<TObjetosGasto> TObjetosGastos { get; set; } = new List<TObjetosGasto>();

    public virtual ICollection<TReserva> TReservas { get; set; } = new List<TReserva>();

    public virtual ICollection<TUnidadesAdministrativa> TUnidadesAdministrativas { get; set; } = new List<TUnidadesAdministrativa>();
}