// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PortalSubastas.Identity.Domain.Models;

public partial class PortalSubastasContext : DbContext
{
    public PortalSubastasContext(DbContextOptions<PortalSubastasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TEstadosUsuario> TEstadosUsuarios { get; set; }

    public virtual DbSet<TJurisdiccionesUsuario> TJurisdiccionesUsuarios { get; set; }

    public virtual DbSet<TModulo> TModulos { get; set; }

    public virtual DbSet<TOrganizacione> TOrganizaciones { get; set; }

    public virtual DbSet<TPersona> TPersonas { get; set; }

    public virtual DbSet<TProveedore> TProveedores { get; set; }

    public virtual DbSet<TProveedoresRepresentante> TProveedoresRepresentantes { get; set; }

    public virtual DbSet<TProveedoresRubro> TProveedoresRubros { get; set; }

    public virtual DbSet<TRole> TRoles { get; set; }

    public virtual DbSet<TRolesModulo> TRolesModulos { get; set; }

    public virtual DbSet<TRubro> TRubros { get; set; }

    public virtual DbSet<TTipoDomicilio> TTiposDomicilio { get; set; }

    public virtual DbSet<TProvincia> TProvincias { get; set; }

    public virtual DbSet<TDomicilio> TDomicilios { get; set; }

    public virtual DbSet<TTiposDocumento> TTiposDocumentos { get; set; }

    public virtual DbSet<TTiposPersona> TTiposPersonas { get; set; }

    public virtual DbSet<TUsuario> TUsuarios { get; set; }

    public virtual DbSet<TVigencia> TVigencias { get; set; }

    public virtual DbSet<TUnidadAdministrativa> TUnidadesAdministrativas { get; set; }

    public virtual DbSet<TObjetoGasto> TObjetosGasto { get; set; }

    public virtual DbSet<TCatalogoBien> TCatalogosBien { get; set; }

    public virtual DbSet<TCategoriaProgramatica> TCategoriasProgramaticas { get; set; }

    public virtual DbSet<TPagina> TPaginas { get; set; }

    public virtual DbSet<TRolesPagina> TRolesPaginas { get; set; }

    public virtual DbSet<TMoneda> TMonedas { get; set; }

    public virtual DbSet<TSubResponsable> TSubResponsables { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresExtension("vector");

        modelBuilder.Entity<TEstadosUsuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_estados_usuario_pkey");

            entity.ToTable("t_estados_usuario", "iam");

            entity.HasIndex(e => e.Descripcion, "t_estados_usuario_descripcion_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TJurisdiccionesUsuario>(entity =>
        {
            entity.HasKey(e => e.IdJurisdiccionUsuario).HasName("t_jurisdicciones_usuarios_pkey");

            entity.ToTable("t_jurisdicciones_usuarios", "iam");

            entity.Property(e => e.IdJurisdiccionUsuario).HasColumnName("id_jurisdiccion_usuario");
            entity.Property(e => e.EsPrincipal)
                .HasDefaultValue(true)
                .HasColumnName("es_principal");
            entity.Property(e => e.FecAsignacion)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_asignacion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdUsuario).HasColumnName("id_usuario");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdOrganizacionNavigation).WithMany(p => p.TJurisdiccionesUsuarios)
                .HasForeignKey(d => d.IdOrganizacion)
                .HasConstraintName("t_jurisdicciones_usuarios_id_organizacion_fkey");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.TJurisdiccionesUsuarios)
                .HasForeignKey(d => d.IdUsuario)
                .HasConstraintName("t_jurisdicciones_usuarios_id_usuario_fkey");
        });

        modelBuilder.Entity<TModulo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_modulos_pkey");

            entity.ToTable("t_modulos", "iam");

            entity.HasIndex(e => e.KeyName, "t_modulos_key_name_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(255)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IconoLucide)
                .HasMaxLength(50)
                .HasColumnName("icono_lucide");
            entity.Property(e => e.KeyName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("key_name");
            entity.Property(e => e.Orden).HasColumnName("orden");
            entity.Property(e => e.RutaFrontend)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("ruta_frontend");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("titulo");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TOrganizacione>(entity =>
        {
            entity.HasKey(e => e.IdOrganizacion).HasName("t_organizaciones_pkey");

            entity.ToTable("t_organizaciones", "iam");

            entity.HasIndex(e => e.Cuit, "t_organizaciones_cuit_key").IsUnique();

            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.Abreviatura)
                .HasMaxLength(20)
                .HasColumnName("abreviatura");
            entity.Property(e => e.Activo)
                .HasDefaultValue(true)
                .HasColumnName("activo");
            entity.Property(e => e.Cuit)
                .HasMaxLength(20)
                .HasColumnName("cuit");
            entity.Property(e => e.FecCreacion)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_creacion");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<TPersona>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_personas_pkey");

            entity.ToTable("t_personas", "iam");

            entity.HasIndex(e => e.NroDocumento, "t_personas_nro_documento_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("apellido");
            entity.Property(e => e.EmailContacto)
                .HasMaxLength(255)
                .HasColumnName("email_contacto");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdTipoDocumento).HasColumnName("id_tipo_documento");
            entity.Property(e => e.IdTipoPersona).HasColumnName("id_tipo_persona");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nombre");
            entity.Property(e => e.NroDocumento)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("nro_documento");
            entity.Property(e => e.Telefono)
                .HasMaxLength(50)
                .HasColumnName("telefono");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdTipoDocumentoNavigation).WithMany(p => p.TPersonas)
                .HasForeignKey(d => d.IdTipoDocumento)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_personas_id_tipo_documento_fkey");

            entity.HasOne(d => d.IdTipoPersonaNavigation).WithMany(p => p.TPersonas)
                .HasForeignKey(d => d.IdTipoPersona)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_personas_id_tipo_persona_fkey");
        });

        modelBuilder.Entity<TProveedore>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_proveedores_pkey");

            entity.ToTable("t_proveedores", "negocio");

            entity.HasIndex(e => e.Cuit, "t_proveedores_cuit_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Cuit)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("cuit");
            entity.Property(e => e.Cup)
                .HasMaxLength(50)
                .HasColumnName("cup");
            entity.Property(e => e.EmailAlternativo)
                .HasMaxLength(255)
                .HasColumnName("email_alternativo");
            entity.Property(e => e.EmailInstitucional)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email_institucional");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdTipoPersona).HasColumnName("id_tipo_persona");
            entity.Property(e => e.RazonSocial)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("razon_social");
            entity.Property(e => e.UrlConstanciaAfip).HasColumnName("url_constancia_afip");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdTipoPersonaNavigation).WithMany(p => p.TProveedores)
                .HasForeignKey(d => d.IdTipoPersona)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_proveedores_id_tipo_persona_fkey");
        });

        modelBuilder.Entity<TProveedoresRepresentante>(entity =>
        {
            entity.HasKey(e => new { e.IdProveedor, e.IdPersona }).HasName("t_proveedores_representantes_pkey");

            entity.ToTable("t_proveedores_representantes", "negocio");

            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");
            entity.Property(e => e.EsApoderado)
                .HasDefaultValue(false)
                .HasColumnName("es_apoderado");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdPersonaNavigation).WithMany(p => p.TProveedoresRepresentantes)
                .HasForeignKey(d => d.IdPersona)
                .HasConstraintName("t_proveedores_representantes_id_persona_fkey");

            entity.HasOne(d => d.IdProveedorNavigation).WithMany(p => p.TProveedoresRepresentantes)
                .HasForeignKey(d => d.IdProveedor)
                .HasConstraintName("t_proveedores_representantes_id_proveedor_fkey");
        });

        modelBuilder.Entity<TProveedoresRubro>(entity =>
        {
            entity.HasKey(e => new { e.IdProveedor, e.IdRubro }).HasName("t_proveedores_rubros_pkey");

            entity.ToTable("t_proveedores_rubros", "negocio");

            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.IdRubro).HasColumnName("id_rubro");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdProveedorNavigation).WithMany(p => p.TProveedoresRubros)
                .HasForeignKey(d => d.IdProveedor)
                .HasConstraintName("t_proveedores_rubros_id_proveedor_fkey");

            entity.HasOne(d => d.IdRubroNavigation).WithMany(p => p.TProveedoresRubros)
                .HasForeignKey(d => d.IdRubro)
                .HasConstraintName("t_proveedores_rubros_id_rubro_fkey");
        });

        modelBuilder.Entity<TRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_roles_pkey");

            entity.ToTable("t_roles", "iam");

            entity.HasIndex(e => e.Nombre, "t_roles_nombre_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(255)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("nombre");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TRolesModulo>(entity =>
        {
            entity.HasKey(e => new { e.IdRol, e.IdModulo }).HasName("t_roles_modulos_pkey");

            entity.ToTable("t_roles_modulos", "iam");

            entity.Property(e => e.IdRol).HasColumnName("id_rol");
            entity.Property(e => e.IdModulo).HasColumnName("id_modulo");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdModuloNavigation).WithMany(p => p.TRolesModulos)
                .HasForeignKey(d => d.IdModulo)
                .HasConstraintName("t_roles_modulos_id_modulo_fkey");

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.TRolesModulos)
                .HasForeignKey(d => d.IdRol)
                .HasConstraintName("t_roles_modulos_id_rol_fkey");
        });

        modelBuilder.Entity<TRubro>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_rubros_pkey");

            entity.ToTable("t_rubros", "negocio");

            entity.HasIndex(e => e.Codigo, "t_rubros_codigo_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("codigo");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("descripcion");
            entity.Property(e => e.IdRubroPadre).HasColumnName("id_rubro_padre");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdRubroPadreNavigation).WithMany(p => p.Hijos)
                .HasForeignKey(d => d.IdRubroPadre)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_rubros_id_rubro_padre_fkey");
        });

        modelBuilder.Entity<TTipoDomicilio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_tipos_domicilio_pkey");
            entity.ToTable("t_tipos_domicilio", "negocio");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion).IsRequired().HasMaxLength(50).HasColumnName("descripcion");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TProvincia>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_provincias_pkey");
            entity.ToTable("t_provincias", "negocio");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Nombre).IsRequired().HasMaxLength(100).HasColumnName("nombre");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TDomicilio>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_domicilios_pkey");
            entity.ToTable("t_domicilios", "negocio");
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");
            entity.Property(e => e.IdTipoDomicilio).HasColumnName("id_tipo_domicilio");
            entity.Property(e => e.Calle).IsRequired().HasMaxLength(255).HasColumnName("calle");
            entity.Property(e => e.Numero).IsRequired().HasMaxLength(20).HasColumnName("numero");
            entity.Property(e => e.Piso).HasMaxLength(20).HasColumnName("piso");
            entity.Property(e => e.Departamento).HasMaxLength(20).HasColumnName("departamento");
            entity.Property(e => e.Barrio).IsRequired().HasMaxLength(255).HasColumnName("barrio");
            entity.Property(e => e.Ciudad).IsRequired().HasMaxLength(255).HasColumnName("ciudad");
            entity.Property(e => e.IdProvincia).HasColumnName("id_provincia");
            entity.Property(e => e.CodigoPostal).IsRequired().HasMaxLength(20).HasColumnName("codigo_postal");
            entity.Property(e => e.Telefono).IsRequired().HasMaxLength(50).HasColumnName("telefono");
            entity.Property(e => e.Fax).HasMaxLength(50).HasColumnName("fax");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");

            entity.HasOne(d => d.IdPersonaNavigation).WithMany(p => p.TDomicilios)
                .HasForeignKey(d => d.IdPersona)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_domicilios_id_persona_fkey");

            entity.HasOne(d => d.IdTipoDomicilioNavigation).WithMany(p => p.TDomicilios)
                .HasForeignKey(d => d.IdTipoDomicilio)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_domicilios_id_tipo_domicilio_fkey");

            entity.HasOne(d => d.IdProvinciaNavigation).WithMany(p => p.TDomicilios)
                .HasForeignKey(d => d.IdProvincia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_domicilios_id_provincia_fkey");
        });

        modelBuilder.Entity<TTiposDocumento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_tipos_documento_pkey");

            entity.ToTable("t_tipos_documento", "iam");

            entity.HasIndex(e => e.Descripcion, "t_tipos_documento_descripcion_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TTiposPersona>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_tipos_persona_pkey");

            entity.ToTable("t_tipos_persona", "iam");

            entity.HasIndex(e => e.Descripcion, "t_tipos_persona_descripcion_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TUsuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_usuarios_pkey");

            entity.ToTable("t_usuarios", "iam");

            entity.HasIndex(e => e.EmailLogin, "t_usuarios_email_login_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AprobadoPor).HasColumnName("aprobado_por");
            entity.Property(e => e.CodigoConfirmacion)
                .HasMaxLength(6)
                .HasColumnName("codigo_confirmacion");
            entity.Property(e => e.EmailConfirmado)
                .HasDefaultValue(false)
                .HasColumnName("email_confirmado");
            entity.Property(e => e.FechaEnvioCodigo)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fecha_envio_codigo");
            entity.Property(e => e.EmailLogin)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email_login");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.FechaAprobacion)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fecha_aprobacion");
            entity.Property(e => e.IdEstado).HasColumnName("id_estado");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");
            entity.Property(e => e.IdRol).HasColumnName("id_rol");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.UltimoAcceso)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("ultimo_acceso");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.AprobadoPorNavigation).WithMany(p => p.InverseAprobadoPorNavigation)
                .HasForeignKey(d => d.AprobadoPor)
                .HasConstraintName("t_usuarios_aprobado_por_fkey");

            entity.HasOne(d => d.IdEstadoNavigation).WithMany(p => p.TUsuarios)
                .HasForeignKey(d => d.IdEstado)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_usuarios_id_estado_fkey");

            entity.HasOne(d => d.IdPersonaNavigation).WithMany(p => p.TUsuarios)
                .HasForeignKey(d => d.IdPersona)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_usuarios_id_persona_fkey");

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.TUsuarios)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_usuarios_id_rol_fkey");
        });

        modelBuilder.Entity<TVigencia>(entity =>
        {
            entity.HasKey(e => e.IdVigencia).HasName("t_vigencias_pkey");

            entity.ToTable("t_vigencias", "negocio");

            entity.HasIndex(e => e.Ejercicio, "t_vigencias_ejercicio_key").IsUnique();

            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.Ejercicio).HasColumnName("ejercicio");
            entity.Property(e => e.ActivoEjecucion)
                .HasDefaultValue(false)
                .HasColumnName("activo_ejecucion");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
        });

        modelBuilder.Entity<TUnidadAdministrativa>(entity =>
        {
            entity.HasKey(e => e.IdUnidadAdm).HasName("t_unidades_administrativas_pkey");

            entity.ToTable("t_unidades_administrativas", "negocio");

            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");
            entity.Property(e => e.NumeroUnidadAdm).HasColumnName("numero_unidad_adm");
            entity.Property(e => e.NombreUnidadAdm)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nombre_unidad_adm");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.Mail)
                .HasMaxLength(255)
                .HasColumnName("mail");
            entity.Property(e => e.Alias)
                .HasMaxLength(255)
                .HasColumnName("alias");
            entity.Property(e => e.Puerto).HasColumnName("puerto");
            entity.Property(e => e.Smtp)
                .HasMaxLength(255)
                .HasColumnName("smtp");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany(p => p.TUnidadesAdministrativas)
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_unidades_administrativas_id_vigencia_fkey");

            entity.HasOne(d => d.IdOrganizacionNavigation).WithMany(p => p.TUnidadesAdministrativas)
                .HasForeignKey(d => d.IdOrganizacion)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_unidades_administrativas_id_organizacion_fkey");
        });

        modelBuilder.Entity<TObjetoGasto>(entity =>
        {
            entity.HasKey(e => e.IdObjetoGasto).HasName("t_objetos_gasto_pkey");

            entity.ToTable("t_objetos_gasto", "negocio");

            entity.HasIndex(e => e.NumeroObjeto, "t_objetos_gasto_numero_key").IsUnique();

            entity.Property(e => e.IdObjetoGasto).HasColumnName("id_objeto_gasto");
            entity.Property(e => e.IdObjetoGastoRel).HasColumnName("id_objeto_gasto_rel");
            entity.Property(e => e.NumeroObjeto)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("numero_objeto");
            entity.Property(e => e.NombreObjeto)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("nombre_objeto");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.ImputaEjecucion)
                .HasDefaultValue(false)
                .HasColumnName("imputa_ejecucion");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdObjetoGastoRelNavigation).WithMany(p => p.InverseIdObjetoGastoRelNavigation)
                .HasForeignKey(d => d.IdObjetoGastoRel)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_objetos_gasto_id_objeto_gasto_rel_fkey");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany()
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_objetos_gasto_id_vigencia_fkey");

            entity.HasOne(d => d.IdOrganizacionNavigation).WithMany()
                .HasForeignKey(d => d.IdOrganizacion)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_objetos_gasto_id_organizacion_fkey");
        });

        modelBuilder.Entity<TCatalogoBien>(entity =>
        {
            entity.HasKey(e => e.IdItem).HasName("t_catalogos_bien_pkey");

            entity.ToTable("t_catalogos_bien", "negocio");

            entity.HasIndex(e => e.Codigo, "t_catalogos_bien_codigo_key").IsUnique();

            entity.Property(e => e.IdItem).HasColumnName("id_item");
            entity.Property(e => e.IdItemRel).HasColumnName("id_item_rel");
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("codigo");
            entity.Property(e => e.NItem)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("n_item");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdObjetoGasto).HasColumnName("id_objeto_gasto");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdItemRelNavigation).WithMany(p => p.InverseIdItemRelNavigation)
                .HasForeignKey(d => d.IdItemRel)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_catalogos_bien_id_item_rel_fkey");

            entity.HasOne(d => d.IdVigenciaNavigation).WithMany()
                .HasForeignKey(d => d.IdVigencia)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_catalogos_bien_id_vigencia_fkey");

            entity.HasOne(d => d.IdOrganizacionNavigation).WithMany()
                .HasForeignKey(d => d.IdOrganizacion)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_catalogos_bien_id_organizacion_fkey");

            entity.HasOne(d => d.IdObjetoGastoNavigation).WithMany(p => p.TCatalogosBien)
                .HasForeignKey(d => d.IdObjetoGasto)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_catalogos_bien_id_objeto_gasto_fkey");
        });

        modelBuilder.Entity<TPagina>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_paginas_pkey");
            entity.ToTable("t_paginas", "iam");
            entity.HasIndex(e => e.KeyName, "t_paginas_key_name_key").IsUnique();
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IdModulo).HasColumnName("id_modulo");
            entity.Property(e => e.KeyName).IsRequired().HasMaxLength(100).HasColumnName("key_name");
            entity.Property(e => e.Titulo).IsRequired().HasMaxLength(100).HasColumnName("titulo");
            entity.Property(e => e.RutaFrontend).HasMaxLength(255).HasColumnName("ruta_frontend");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdModuloNavigation).WithMany(p => p.TPaginas)
                .HasForeignKey(d => d.IdModulo)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_paginas_id_modulo_fkey");
        });

        modelBuilder.Entity<TRolesPagina>(entity =>
        {
            entity.HasKey(e => new { e.IdRol, e.IdPagina }).HasName("t_roles_paginas_pkey");
            entity.ToTable("t_roles_paginas", "iam");
            entity.Property(e => e.IdRol).HasColumnName("id_rol");
            entity.Property(e => e.IdPagina).HasColumnName("id_pagina");

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.TRolesPaginas)
                .HasForeignKey(d => d.IdRol)
                .HasConstraintName("t_roles_paginas_id_rol_fkey");

            entity.HasOne(d => d.IdPaginaNavigation).WithMany(p => p.TRolesPaginas)
                .HasForeignKey(d => d.IdPagina)
                .HasConstraintName("t_roles_paginas_id_pagina_fkey");
        });

        modelBuilder.Entity<TCategoriaProgramatica>(entity =>
        {
            entity.HasKey(e => e.IdCatProg).HasName("t_categorias_programaticas_pkey");
            entity.ToTable("t_categorias_programaticas", "negocio");
            entity.Property(e => e.IdCatProg).HasColumnName("id_cat_prog");
            entity.Property(e => e.IdCatProgRel).HasColumnName("id_cat_prog_rel");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");
            entity.Property(e => e.IdVigencia).HasColumnName("id_vigencia");
            entity.Property(e => e.Codigo).HasColumnName("codigo");
            entity.Property(e => e.Nombre).IsRequired().HasMaxLength(500).HasColumnName("nombre");
            entity.Property(e => e.Naturaleza).HasMaxLength(2).HasColumnName("naturaleza");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");

            entity.HasOne(d => d.IdCatProgRelNavigation).WithMany(p => p.InverseIdCatProgRelNavigation)
                .HasForeignKey(d => d.IdCatProgRel).OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_categorias_programaticas_id_cat_prog_rel_fkey");
            entity.HasOne(d => d.IdOrganizacionNavigation).WithMany()
                .HasForeignKey(d => d.IdOrganizacion).OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_categorias_programaticas_id_organizacion_fkey");
            entity.HasOne(d => d.IdUnidadAdmNavigation).WithMany()
                .HasForeignKey(d => d.IdUnidadAdm).OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_categorias_programaticas_id_unidad_adm_fkey");
            entity.HasOne(d => d.IdVigenciaNavigation).WithMany()
                .HasForeignKey(d => d.IdVigencia).OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_categorias_programaticas_id_vigencia_fkey");
        });

        modelBuilder.Entity<TMoneda>(entity =>
        {
            entity.HasKey(e => e.IdMoneda).HasName("t_moneda_pkey");
            entity.ToTable("t_moneda", "negocio");
            entity.Property(e => e.IdMoneda).HasColumnName("id_moneda");
            entity.Property(e => e.Simbolo).HasMaxLength(10).HasColumnName("simbolo");
            entity.Property(e => e.Nombre).IsRequired().HasMaxLength(200).HasColumnName("nombre");
            entity.Property(e => e.Descripcion).HasMaxLength(500).HasColumnName("descripcion");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
        });

        modelBuilder.Entity<TSubResponsable>(entity =>
        {
            entity.HasKey(e => e.IdSubResponsable).HasName("t_sub_responsables_pkey");
            entity.ToTable("t_sub_responsables", "negocio");
            entity.Property(e => e.IdSubResponsable).HasColumnName("id_sub_responsable");
            entity.Property(e => e.Codigo).HasMaxLength(20).HasColumnName("codigo");
            entity.Property(e => e.Nombre).IsRequired().HasMaxLength(500).HasColumnName("nombre");
            entity.Property(e => e.UsrIng).HasMaxLength(100).HasDefaultValueSql("'SISTEMA'::character varying").HasColumnName("usr_ing");
            entity.Property(e => e.FecIng).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp without time zone").HasColumnName("fec_ing");
            entity.Property(e => e.UsrMod).HasMaxLength(100).HasColumnName("usr_mod");
            entity.Property(e => e.FecMod).HasColumnType("timestamp without time zone").HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja).HasMaxLength(100).HasColumnName("usr_baja");
            entity.Property(e => e.FecBaja).HasColumnType("timestamp without time zone").HasColumnName("fec_baja");
            entity.Property(e => e.IdSubRespRel).HasColumnName("id_sub_resp_rel");
            entity.Property(e => e.Vigente).HasColumnName("vigente");
            entity.Property(e => e.IdUnidadAdm).HasColumnName("id_unidad_adm");

            entity.HasOne(d => d.IdSubRespRelNavigation).WithMany(p => p.InverseIdSubRespRelNavigation)
                .HasForeignKey(d => d.IdSubRespRel).OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_sub_responsables_id_sub_resp_rel_fkey");
            entity.HasOne(d => d.IdUnidadAdmNavigation).WithMany()
                .HasForeignKey(d => d.IdUnidadAdm).OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_sub_responsables_id_unidad_adm_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}