// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PortalSubastas.Identity.Domain.Models;

public partial class PortalSubastasContext : DbContext
{
    public PortalSubastasContext(DbContextOptions<PortalSubastasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TEstadosUsuario> TEstadosUsuarios { get; set; }

    public virtual DbSet<TJurisdiccionesUsuario> TJurisdiccionesUsuarios { get; set; }

    public virtual DbSet<TModulo> TModulos { get; set; }

    public virtual DbSet<TOrganizacione> TOrganizaciones { get; set; }

    public virtual DbSet<TPersona> TPersonas { get; set; }

    public virtual DbSet<TProveedore> TProveedores { get; set; }

    public virtual DbSet<TProveedoresRepresentante> TProveedoresRepresentantes { get; set; }

    public virtual DbSet<TProveedoresRubro> TProveedoresRubros { get; set; }

    public virtual DbSet<TRole> TRoles { get; set; }

    public virtual DbSet<TRolesModulo> TRolesModulos { get; set; }

    public virtual DbSet<TRubro> TRubros { get; set; }

    public virtual DbSet<TTiposDocumento> TTiposDocumentos { get; set; }

    public virtual DbSet<TTiposPersona> TTiposPersonas { get; set; }

    public virtual DbSet<TUsuario> TUsuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TEstadosUsuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_estados_usuario_pkey");

            entity.ToTable("t_estados_usuario", "iam");

            entity.HasIndex(e => e.Descripcion, "t_estados_usuario_descripcion_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TJurisdiccionesUsuario>(entity =>
        {
            entity.HasKey(e => e.IdJurisdiccionUsuario).HasName("t_jurisdicciones_usuarios_pkey");

            entity.ToTable("t_jurisdicciones_usuarios", "iam");

            entity.Property(e => e.IdJurisdiccionUsuario).HasColumnName("id_jurisdiccion_usuario");
            entity.Property(e => e.EsPrincipal)
                .HasDefaultValue(true)
                .HasColumnName("es_principal");
            entity.Property(e => e.FecAsignacion)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_asignacion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.IdUsuario).HasColumnName("id_usuario");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdOrganizacionNavigation).WithMany(p => p.TJurisdiccionesUsuarios)
                .HasForeignKey(d => d.IdOrganizacion)
                .HasConstraintName("t_jurisdicciones_usuarios_id_organizacion_fkey");

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.TJurisdiccionesUsuarios)
                .HasForeignKey(d => d.IdUsuario)
                .HasConstraintName("t_jurisdicciones_usuarios_id_usuario_fkey");
        });

        modelBuilder.Entity<TModulo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_modulos_pkey");

            entity.ToTable("t_modulos", "iam");

            entity.HasIndex(e => e.KeyName, "t_modulos_key_name_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(255)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IconoLucide)
                .HasMaxLength(50)
                .HasColumnName("icono_lucide");
            entity.Property(e => e.KeyName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("key_name");
            entity.Property(e => e.Orden).HasColumnName("orden");
            entity.Property(e => e.RutaFrontend)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("ruta_frontend");
            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("titulo");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TOrganizacione>(entity =>
        {
            entity.HasKey(e => e.IdOrganizacion).HasName("t_organizaciones_pkey");

            entity.ToTable("t_organizaciones", "iam");

            entity.HasIndex(e => e.Cuit, "t_organizaciones_cuit_key").IsUnique();

            entity.Property(e => e.IdOrganizacion).HasColumnName("id_organizacion");
            entity.Property(e => e.Abreviatura)
                .HasMaxLength(20)
                .HasColumnName("abreviatura");
            entity.Property(e => e.Activo)
                .HasDefaultValue(true)
                .HasColumnName("activo");
            entity.Property(e => e.Cuit)
                .HasMaxLength(20)
                .HasColumnName("cuit");
            entity.Property(e => e.FecCreacion)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_creacion");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nombre");
        });

        modelBuilder.Entity<TPersona>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_personas_pkey");

            entity.ToTable("t_personas", "iam");

            entity.HasIndex(e => e.NroDocumento, "t_personas_nro_documento_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("apellido");
            entity.Property(e => e.EmailContacto)
                .HasMaxLength(255)
                .HasColumnName("email_contacto");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdTipoDocumento).HasColumnName("id_tipo_documento");
            entity.Property(e => e.IdTipoPersona).HasColumnName("id_tipo_persona");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nombre");
            entity.Property(e => e.NroDocumento)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("nro_documento");
            entity.Property(e => e.Telefono)
                .HasMaxLength(50)
                .HasColumnName("telefono");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdTipoDocumentoNavigation).WithMany(p => p.TPersonas)
                .HasForeignKey(d => d.IdTipoDocumento)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_personas_id_tipo_documento_fkey");

            entity.HasOne(d => d.IdTipoPersonaNavigation).WithMany(p => p.TPersonas)
                .HasForeignKey(d => d.IdTipoPersona)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_personas_id_tipo_persona_fkey");
        });

        modelBuilder.Entity<TProveedore>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_proveedores_pkey");

            entity.ToTable("t_proveedores", "negocio");

            entity.HasIndex(e => e.Cuit, "t_proveedores_cuit_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Cuit)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("cuit");
            entity.Property(e => e.Cup)
                .HasMaxLength(50)
                .HasColumnName("cup");
            entity.Property(e => e.EmailAlternativo)
                .HasMaxLength(255)
                .HasColumnName("email_alternativo");
            entity.Property(e => e.EmailInstitucional)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email_institucional");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.IdTipoPersona).HasColumnName("id_tipo_persona");
            entity.Property(e => e.RazonSocial)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("razon_social");
            entity.Property(e => e.UrlConstanciaAfip).HasColumnName("url_constancia_afip");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdTipoPersonaNavigation).WithMany(p => p.TProveedores)
                .HasForeignKey(d => d.IdTipoPersona)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_proveedores_id_tipo_persona_fkey");
        });

        modelBuilder.Entity<TProveedoresRepresentante>(entity =>
        {
            entity.HasKey(e => new { e.IdProveedor, e.IdPersona }).HasName("t_proveedores_representantes_pkey");

            entity.ToTable("t_proveedores_representantes", "negocio");

            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");
            entity.Property(e => e.EsApoderado)
                .HasDefaultValue(false)
                .HasColumnName("es_apoderado");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdPersonaNavigation).WithMany(p => p.TProveedoresRepresentantes)
                .HasForeignKey(d => d.IdPersona)
                .HasConstraintName("t_proveedores_representantes_id_persona_fkey");

            entity.HasOne(d => d.IdProveedorNavigation).WithMany(p => p.TProveedoresRepresentantes)
                .HasForeignKey(d => d.IdProveedor)
                .HasConstraintName("t_proveedores_representantes_id_proveedor_fkey");
        });

        modelBuilder.Entity<TProveedoresRubro>(entity =>
        {
            entity.HasKey(e => new { e.IdProveedor, e.IdRubro }).HasName("t_proveedores_rubros_pkey");

            entity.ToTable("t_proveedores_rubros", "negocio");

            entity.Property(e => e.IdProveedor).HasColumnName("id_proveedor");
            entity.Property(e => e.IdRubro).HasColumnName("id_rubro");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdProveedorNavigation).WithMany(p => p.TProveedoresRubros)
                .HasForeignKey(d => d.IdProveedor)
                .HasConstraintName("t_proveedores_rubros_id_proveedor_fkey");

            entity.HasOne(d => d.IdRubroNavigation).WithMany(p => p.TProveedoresRubros)
                .HasForeignKey(d => d.IdRubro)
                .HasConstraintName("t_proveedores_rubros_id_rubro_fkey");
        });

        modelBuilder.Entity<TRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_roles_pkey");

            entity.ToTable("t_roles", "iam");

            entity.HasIndex(e => e.Nombre, "t_roles_nombre_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .HasMaxLength(255)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("nombre");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TRolesModulo>(entity =>
        {
            entity.HasKey(e => new { e.IdRol, e.IdModulo }).HasName("t_roles_modulos_pkey");

            entity.ToTable("t_roles_modulos", "iam");

            entity.Property(e => e.IdRol).HasColumnName("id_rol");
            entity.Property(e => e.IdModulo).HasColumnName("id_modulo");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.IdModuloNavigation).WithMany(p => p.TRolesModulos)
                .HasForeignKey(d => d.IdModulo)
                .HasConstraintName("t_roles_modulos_id_modulo_fkey");

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.TRolesModulos)
                .HasForeignKey(d => d.IdRol)
                .HasConstraintName("t_roles_modulos_id_rol_fkey");
        });

        modelBuilder.Entity<TRubro>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_rubros_pkey");

            entity.ToTable("t_rubros", "negocio");

            entity.HasIndex(e => e.Codigo, "t_rubros_codigo_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("codigo");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TTiposDocumento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_tipos_documento_pkey");

            entity.ToTable("t_tipos_documento", "iam");

            entity.HasIndex(e => e.Descripcion, "t_tipos_documento_descripcion_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TTiposPersona>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_tipos_persona_pkey");

            entity.ToTable("t_tipos_persona", "iam");

            entity.HasIndex(e => e.Descripcion, "t_tipos_persona_descripcion_key").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("descripcion");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");
        });

        modelBuilder.Entity<TUsuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("t_usuarios_pkey");

            entity.ToTable("t_usuarios", "iam");

            entity.HasIndex(e => e.EmailLogin, "t_usuarios_email_login_key").IsUnique();

            entity.Property(e => e.Id)
                .HasDefaultValueSql("gen_random_uuid()")
                .HasColumnName("id");
            entity.Property(e => e.AprobadoPor).HasColumnName("aprobado_por");
            entity.Property(e => e.EmailLogin)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("email_login");
            entity.Property(e => e.FecBaja)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_baja");
            entity.Property(e => e.FecIng)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_ing");
            entity.Property(e => e.FecMod)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fec_mod");
            entity.Property(e => e.FechaAprobacion)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("fecha_aprobacion");
            entity.Property(e => e.IdEstado).HasColumnName("id_estado");
            entity.Property(e => e.IdPersona).HasColumnName("id_persona");
            entity.Property(e => e.IdRol).HasColumnName("id_rol");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("password_hash");
            entity.Property(e => e.UltimoAcceso)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("ultimo_acceso");
            entity.Property(e => e.UsrBaja)
                .HasMaxLength(100)
                .HasColumnName("usr_baja");
            entity.Property(e => e.UsrIng)
                .HasMaxLength(100)
                .HasDefaultValueSql("'SISTEMA'::character varying")
                .HasColumnName("usr_ing");
            entity.Property(e => e.UsrMod)
                .HasMaxLength(100)
                .HasColumnName("usr_mod");

            entity.HasOne(d => d.AprobadoPorNavigation).WithMany(p => p.InverseAprobadoPorNavigation)
                .HasForeignKey(d => d.AprobadoPor)
                .HasConstraintName("t_usuarios_aprobado_por_fkey");

            entity.HasOne(d => d.IdEstadoNavigation).WithMany(p => p.TUsuarios)
                .HasForeignKey(d => d.IdEstado)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_usuarios_id_estado_fkey");

            entity.HasOne(d => d.IdPersonaNavigation).WithMany(p => p.TUsuarios)
                .HasForeignKey(d => d.IdPersona)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_usuarios_id_persona_fkey");

            entity.HasOne(d => d.IdRolNavigation).WithMany(p => p.TUsuarios)
                .HasForeignKey(d => d.IdRol)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("t_usuarios_id_rol_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}