// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PortalSubastas.Identity.Domain.Models;

public partial class TJurisdiccionesUsuario : IFullAuditableEntity
{
    public int IdJurisdiccionUsuario { get; set; }

    public Guid IdUsuario { get; set; }

    public int IdOrganizacion { get; set; }

    public DateTime? FecAsignacion { get; set; }

    public bool? EsPrincipal { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public virtual TOrganizacione IdOrganizacionNavigation { get; set; }

    public virtual TUsuario IdUsuarioNavigation { get; set; }
}