// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PortalSubastas.Identity.Domain.Models;

public partial class TModulo : IFullAuditableEntity
{
    public int Id { get; set; }

    public string KeyName { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public string IconoLucide { get; set; }

    public string RutaFrontend { get; set; }

    public int Orden { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public virtual ICollection<TRolesModulo> TRolesModulos { get; set; } = new List<TRolesModulo>();
}