// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PortalSubastas.Identity.Domain.Models;

public partial class TOrganizacione 
{
    public int IdOrganizacion { get; set; } 

    public string Nombre { get; set; }

    public string Cuit { get; set; }

    public string Abreviatura { get; set; }

    public bool? Activo { get; set; }

    public DateTime? FecCreacion { get; set; }

    public virtual ICollection<TJurisdiccionesUsuario> TJurisdiccionesUsuarios { get; set; } = new List<TJurisdiccionesUsuario>();
    public virtual ICollection<TUnidadAdministrativa> TUnidadesAdministrativas { get; set; } = new List<TUnidadAdministrativa>();
}