// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PortalSubastas.Identity.Domain.Models;

public partial class TPersona : IFullAuditableEntity
{
    public int Id { get; set; }

    public int IdTipoPersona { get; set; }

    public int IdTipoDocumento { get; set; }

    public string NroDocumento { get; set; }

    public string Telefono { get; set; }

    public string EmailContacto { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public virtual TTiposDocumento IdTipoDocumentoNavigation { get; set; }

    public virtual TTiposPersona IdTipoPersonaNavigation { get; set; }

    public virtual ICollection<TProveedoresRepresentante> TProveedoresRepresentantes { get; set; } = new List<TProveedoresRepresentante>();

    public virtual ICollection<TUsuario> TUsuarios { get; set; } = new List<TUsuario>();
}