// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PortalSubastas.Identity.Domain.Models;

public partial class TProveedoresRepresentante : IFullAuditableEntity
{
    public int IdProveedor { get; set; }

    public int IdPersona { get; set; }

    public bool? EsApoderado { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public virtual TPersona IdPersonaNavigation { get; set; }

    public virtual TProveedore IdProveedorNavigation { get; set; }
}