// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PortalSubastas.Identity.Domain.Models;

public partial class TRubro : IFullAuditableEntity
{
    public int Id { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public virtual ICollection<TProveedoresRubro> TProveedoresRubros { get; set; } = new List<TProveedoresRubro>();
}