// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PortalSubastas.Identity.Domain.Models;

public partial class TUsuario : IFullAuditableEntity
{
    public Guid Id { get; set; }

    public int IdPersona { get; set; }

    public int IdRol { get; set; }

    public int IdEstado { get; set; }

    public string EmailLogin { get; set; }

    public string PasswordHash { get; set; }

    public DateTime? UltimoAcceso { get; set; }

    public string UsrIng { get; set; }

    public DateTime? FecIng { get; set; }

    public string UsrMod { get; set; }

    public DateTime? FecMod { get; set; }

    public string UsrBaja { get; set; }

    public DateTime? FecBaja { get; set; }

    public DateTime? FechaAprobacion { get; set; }

    public Guid? AprobadoPor { get; set; }

    public virtual TUsuario AprobadoPorNavigation { get; set; }

    public virtual TEstadosUsuario IdEstadoNavigation { get; set; }

    public virtual TPersona IdPersonaNavigation { get; set; }

    public virtual TRole IdRolNavigation { get; set; }

    public virtual ICollection<TUsuario> InverseAprobadoPorNavigation { get; set; } = new List<TUsuario>();

    public virtual ICollection<TJurisdiccionesUsuario> TJurisdiccionesUsuarios { get; set; } = new List<TJurisdiccionesUsuario>();
}